myshop/coupons/urls.py
from django.conf.urls import url
from . import views


urlpatterns = [
    url(r'^apply/$', views.coupon_apply, name='apply'),
]

myshop/korzina/urls.py
from django.conf.urls import url
from . import views


urlpatterns = [
    url(r'^$', views.korzina_detail, name='korzina_detail'),
    url(r'^add/(?P<product_id>\d+)/$', views.korzina_add, name='korzina_add'),
    url(r'^remove/(?P<product_id>\d+)/$', views.korzina_remove, name='korzina_remove'),
]

myshop/myshop/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls.i18n import i18n_patterns
from django.utils.translation import gettext_lazy as _

urlpatterns = i18n_patterns(
    url(r'^admin/', include(admin.site.urls)),
    url(_(r'^korzina/'), include('korzina.urls', namespace='korzina')),
    url(_(r'^orders/'), include('orders.urls', namespace='orders')),
    url(_(r'^coupons/'), include('coupons.urls', namespace='coupons')),
    url(r'^rosetta/', include('rosetta.urls')),
    url(r'^', include('shop.urls', namespace='shop')),

)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

myshop/orders/urls.py
from django.conf.urls import url
from . import views
from django.utils.translation import gettext_lazy as _


urlpatterns = [
    url(_(r'^create/$'), views.order_create, name='order_create'),
]

myshop/shop/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.product_list, name='product_list'),
    url(r'^(?P<category_slug>[-\w]+)/$',
        views.product_list,
        name='product_list_by_category'),
    url(r'^(?P<id>\d+)/(?P<slug>[-\w]+)/$',
        views.product_detail,
        name='product_detail'),
]

myshop/korzina/models.py
from django.db import models

# Create your models here.

myshop/shop/models.py
from django.db import models
from django.core.urlresolvers import reverse
from parler.models import TranslatableModel, TranslatedFields

class Category(TranslatableModel):
    translations = TranslatedFields(
        name=models.CharField(max_length=200, db_index=True),
        slug=models.SlugField(max_length=200, db_index=True, unique=True)
    )

    def get_absolute_url(self):
        return reverse('shop:product_list_by_category',
                       args=[self.slug])

    class Meta:
        # ordering = ('name',)
        verbose_name = 'Категория'
        verbose_name_plural = 'Категории'

    def __str__(self):
        return self.name


class Product(TranslatableModel):
    translations = TranslatedFields(
        name=models.CharField(max_length=200, db_index=True),
        slug=models.SlugField(max_length=200, db_index=True),
        description=models.TextField(blank=True)
    )
    category = models.ForeignKey(Category, related_name='products')
    image = models.ImageField(upload_to='products/%Y/%m/%d', blank=True)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    stock = models.PositiveIntegerField()
    available = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    def get_absolute_url(self):
        return reverse('shop:product_detail',
                       args=[self.id, self.slug])

    class Meta:
        ordering = ('-created',)
        # index_together = (('id', 'slug'),)

    def __str__(self):
        return self.name

myshop/korzina/forms.py
from django import forms
from django.utils.translation import gettext_lazy as _

PRODUCT_QUANTITY_CHOICES = [(i, str(i)) for i in range(1, 21)]


class korzinaAddProductForm(forms.Form):
    quantity = forms.TypedChoiceField(choices=PRODUCT_QUANTITY_CHOICES, coerce=int, label=_('Quantity'))
    update = forms.BooleanField(required=False, initial=False, widget=forms.HiddenInput)

myshop/korzina/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST
from shop.models import Product
from .korzina import Korzina
from .forms import korzinaAddProductForm
from coupons.forms import CouponApplyForm


@require_POST
def korzina_add(request, product_id):
    korzina = Korzina(request)
    product = get_object_or_404(Product, id=product_id)
    form = korzinaAddProductForm(request.POST)
    if form.is_valid():
        cd = form.cleaned_data
        korzina.add(product=product,
                 quantity=cd['quantity'],
                 update_quantity=cd['update'])
    return redirect('korzina:korzina_detail')

def korzina_remove(request, product_id):
    korzina = Korzina(request)
    product = get_object_or_404(Product, id=product_id)
    korzina.remove(product)
    return redirect('korzina:korzina_detail')

def korzina_detail(request):
    korzina = Korzina(request)
    for item in korzina:
        item['update_quantity_form'] = korzinaAddProductForm(
            initial={'quantity': item['quantity'],
                     'update': True})
    coupon_apply_form = CouponApplyForm()
    return render(request,
                  'korzina/detail.html',
                  {'korzina': korzina,
                   'coupon_apply_form': coupon_apply_form})

myshop/shop/views.py
from django.shortcuts import render, get_object_or_404
from .models import Category, Product
from korzina.forms import korzinaAddProductForm



def product_list(request, category_slug=None):
    category = None
    categories = Category.objects.all()
    products = Product.objects.filter(available=True)
    if category_slug:
        language = request.LANGUAGE_CODE
        category = get_object_or_404(Category,
                                     translations__language_code=language,
                                     translations__slug=category_slug)
        products = products.filter(category=category)
    return render(request,
                  'shop/product/list.html',
                  {'category': category,
                   'categories': categories,
                   'products': products})


def product_detail(request, id, slug):
    language = request.LANGUAGE_CODE
    product = get_object_or_404(Product,
                                id=id,
                                translations__language_code=language,
                                translations__slug=slug,
                                available=True)
    korzina_product_form = korzinaAddProductForm()
    return render(request, 'shop/product/detail.html', {'product': product,
                                                        'korzina_product_form': korzina_product_form})

myshop/shop/templates/korzina/detail.html
{% extends "shop/base.html" %}
{% load i18n %}
{% load static %}
{% block title %}
    <h1 class="text-center">Your shopping korzina</h1>
{% endblock %}
{% block content %}
    <h1>{% trans "Your shopping korzina" %}</h1>
    <table class="korzina">
        <thead>
        <tr>
            <th>{% trans "Image" %}</th>
            <th>{% trans "Product" %}</th>
            <th>{% trans "Quantity" %}</th>
            <th>{% trans "Remove" %}</th>
            <th>{% trans "Unit price" %}</th>
            <th>{% trans "Price" %}</th>
        </tr>
        </thead>
        <tbody>
        {% for item in korzina %}
            {% with product=item.product %}
                <tr>
                    <td>
                        <a href="{{ product.get_absolute_url }}">
                            <img src="
                                {% if product.image %}
                                    {{ product.image.url }}
                                {% else %}
                                    {% static 'shop/img/no_image.png' %}
                                {% endif %}">
                        </a>
                    </td>
                    <td>{{ product.name }}</td>
                    <td>{{ item.quantity }}</td>
                    <td><a href="{% url 'korzina:korzina_remove' product.id%}">{% trans "Remove" %}</a></td>
                    <td class="num">${{ item.price }}</td>
                    <td class="num">${{ item.total_price }}</td>
                </tr>
            {% endwith %}
        {% endfor %}
        {% if korzina.coupon %}
    <tr class="subtotal">
        <td>Subtotal</td>
        <td colspan="4"></td>
        <td class="num">${{ korzina.get_total_price }}</td>
    </tr>
    <tr>
        <td>
            "{{ korzina.coupon.code }}" coupon
            ({{ korzina.coupon.discount }}% off)
        </td>
        <td colspan="4"></td>
        <td class="num neg">
            - ${{ korzina.get_discount|floatformat:"2" }}
        </td>
    </tr>
{% endif %}
<tr class="total">
    <td>{% trans "Total" %}</td>
    <td colspan="4"></td>
    <td class="num">
        ${{ korzina.get_total_price_after_discount|floatformat:"2" }}
    </td>
</tr>
        </tbody>
    </table>
    <form action="{% url 'coupons:apply' %}" method="post">
    {{ coupon_apply_form }}
    <input type="submit" value="{% trans "Apply" %}">
    {% csrf_token %}
    </form>
    <p class="text-right">
        <a href="{% url 'shop:product_list' %}" class="button light">{% trans "Continue shopping" %}</a>
        <a href="{% url 'orders:order_create' %}" class="button">
        {% trans "Checkout" %}</a>
    </p>
{% endblock %}