myshop/korzina/urls.py
from django.conf.urls import url
from . import views


urlpatterns = [
    url(r'^$', views.korzina_detail, name='korzina_detail'),
    url(r'^add/(?P<product_id>\d+)/$', views.korzina_add, name='korzina_add'),
    url(r'^remove/(?P<product_id>\d+)/$', views.korzina_remove, name='korzina_remove'),
]

myshop/myshop/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls.i18n import i18n_patterns
from django.utils.translation import gettext_lazy as _

urlpatterns = i18n_patterns(
    url(r'^admin/', include(admin.site.urls)),
    url(_(r'^korzina/'), include('korzina.urls', namespace='korzina')),
    url(_(r'^orders/'), include('orders.urls', namespace='orders')),
    url(_(r'^coupons/'), include('coupons.urls', namespace='coupons')),
    url(r'^rosetta/', include('rosetta.urls')),
    url(r'^', include('shop.urls', namespace='shop')),

)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

myshop/shop/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.product_list, name='product_list'),
    url(r'^(?P<category_slug>[-\w]+)/$',
        views.product_list,
        name='product_list_by_category'),
    url(r'^(?P<id>\d+)/(?P<slug>[-\w]+)/$',
        views.product_detail,
        name='product_detail'),
]

myshop/shop/models.py
from django.db import models
from django.core.urlresolvers import reverse
from parler.models import TranslatableModel, TranslatedFields

class Category(TranslatableModel):
    translations = TranslatedFields(
        name=models.CharField(max_length=200, db_index=True),
        slug=models.SlugField(max_length=200, db_index=True, unique=True)
    )

    def get_absolute_url(self):
        return reverse('shop:product_list_by_category',
                       args=[self.slug])

    class Meta:
        # ordering = ('name',)
        verbose_name = 'Категория'
        verbose_name_plural = 'Категории'

    def __str__(self):
        return self.name


class Product(TranslatableModel):
    translations = TranslatedFields(
        name=models.CharField(max_length=200, db_index=True),
        slug=models.SlugField(max_length=200, db_index=True),
        description=models.TextField(blank=True)
    )
    category = models.ForeignKey(Category, related_name='products')
    image = models.ImageField(upload_to='products/%Y/%m/%d', blank=True)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    stock = models.PositiveIntegerField()
    available = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    def get_absolute_url(self):
        return reverse('shop:product_detail',
                       args=[self.id, self.slug])

    class Meta:
        ordering = ('-created',)
        # index_together = (('id', 'slug'),)

    def __str__(self):
        return self.name

myshop/shop/views.py
from django.shortcuts import render, get_object_or_404
from .models import Category, Product
from korzina.forms import korzinaAddProductForm



def product_list(request, category_slug=None):
    category = None
    categories = Category.objects.all()
    products = Product.objects.filter(available=True)
    if category_slug:
        language = request.LANGUAGE_CODE
        category = get_object_or_404(Category,
                                     translations__language_code=language,
                                     translations__slug=category_slug)
        products = products.filter(category=category)
    return render(request,
                  'shop/product/list.html',
                  {'category': category,
                   'categories': categories,
                   'products': products})


def product_detail(request, id, slug):
    language = request.LANGUAGE_CODE
    product = get_object_or_404(Product,
                                id=id,
                                translations__language_code=language,
                                translations__slug=slug,
                                available=True)
    korzina_product_form = korzinaAddProductForm()
    return render(request, 'shop/product/detail.html', {'product': product,
                                                        'korzina_product_form': korzina_product_form})

myshop/shop/templates/shop/base.html
{% load i18n %}
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8"/>
    <title>
        {% block title %}{% trans "MobileMart" %}{% endblock %}
    </title>
    <link href="{% static 'shop/css/base.css' %}" rel="stylesheet">
</head>
<body>
<div id="header">
    <a href="/" class="logo">{% trans "MobileMart" %}</a>
    {% get_current_language as LANGUAGE_CODE %}
    {% get_available_languages as LANGUAGES %}
    {% get_language_info_list for LANGUAGES as languages %}
    <div class="languages">
        <p>{% trans "Language" %}:</p>
        <ul class="languages">
            {% for language in languages %}
                <li>
                    <a href="/{{ language.code }}/" {% if language.code == LANGUAGE_CODE %} class="selected"{% endif %}>
                        {{ language.name_local }}
                    </a>
                </li>
            {% endfor %}
        </ul>
    </div>
</div>
<div id="subheader">
    <div class="logo1">
    <a href="{% url "shop:product_list" %}">
        <img src="{% static 'shop/img/logot.avif' %}" alt="Логотип">
     </a>
    </div>
    <div class="korzina">
        {% with total_items=korzina|length %}
            {% if korzina|length > 0 %}
                {% trans "Your korzina" %}:
                <a href="{% url 'korzina:korzina_detail' %}">
                    {% blocktrans with total_items_plural=total_items|pluralize total_price=korzina.get_total_price %}
                        {{ total_items }} item{{ total_items_plural }},
                        ${{ total_price }}
                    {% endblocktrans %}
                </a>
            {% else %}
                {% trans "Your korzina is empty." %}
            {% endif %}
        {% endwith %}
    </div>
</div>
<div id="content">
    {% block content %}
    {% endblock %}
</div>
<div id="footer">
    <div class="footer-section" style="float: left; width: 45%; padding: 0 20px;">
        <h3>{% trans "About us" %}</h3>
        <p>{% trans "Our online store offers a wide range of smartphones and accessories from leading manufacturers. We guarantee high quality products and provide convenient delivery and payment terms." %}</p>
    </div>
    <div class="footer-section" style="float: right; width: 45%; text-align: right; padding: 0 20px;">
        <h3>{% trans "Contacts" %}</h3>
        <p>{% trans "Address" %}: {% trans "Moscow" %}, {% trans "Pushkin St." %}, {% trans "12" %}</p>
        <p>{% trans "Phone" %}: {% trans "+7 (495) 123-45-67" %}</p>
        <p>{% trans "Email" %}: {% trans "info@myshop.com" %}</p>
    </div>
</div>
</body>
</html>